const context = "PENGGUNAAN DANA YANG DIPEROLEH DARI HASIL PENAWARAN UMUM 4 III. PERNYATAAN UTANG 7 IV. IKHTISAR DATA KEUANGAN PENTING 13 V. ANALISIS DAN PEMBAHASAN OLEH MANAJEMEN 19 VI. FAKTOR RISIKO 39 VII. KEJADIAN PENTING YANG TERJADI SETELAH TANGGAL LAPORAN AKUNTAN PUBLIK 44 VIII. KETERANGAN TENTANG PERSEROAN, KEGIATAN USAHA, SERTA KECENDERUNGAN DAN PROSPEK USAHA 45 1. RIWAYAT SINGKAT PERSEROAN 45 2. PERSETUJUAN PENAWARAN UMUM PERDANA SAHAM 46 3. KEJADIAN PENTING YANG MEMPENGARUHI PERKEMBANGAN USAHA PERSEROAN 47 4. PERKEMBANGAN KEPEMILIKAN SAHAM PERSEROAN 47 5. PERIZINAN YANG DIMILIKI PERSEROAN 49 6. TRANSAKSI DAN PERJANJIAN-PERJANJIAN PENTING DENGAN PIHAK KETIGA 53 7. TRANSAKSI DAN PERJANJIAN-PERJANJIAN DENGAN PIHAK AFILIASI 69 8. KETERANGAN MENGENAI ASET TETAP PERSEROAN 70 9. KETERANGAN SINGKAT MENGENAI PEMEGANG SAHAM PERSEROAN BERBENTUK BADAN HUKUM DENGAN KEPEMILIKAN SAHAM LEBIH DARI 5% (LIMA PERSEN) 79 10. PENGURUSAN, PENGAWASAN DAN TATA KELOLA PERUSAHAAN 80 11. TANGGUNG JAWAB SOSIAL (CORPORAT";

const test1 = /\.{4,}/.test(context);
const test2 = /\.\s*\.\s*\./.test(context);
const test3 = /\b(?:III|IV|V|VI|VII)\b\s*(?:\.|\s)*\b(?:PERNYATAAN|IKHTISAR|ANALISIS|FAKTOR)\b/i.test(context);

console.log('test1 (dots):', test1);
console.log('test2 (spaced dots):', test2);
console.log('test3 (roman headings):', test3);

const matchRoman = context.match(/\b(?:III|IV|V|VI|VII)\b\s*(?:\.|\s)*\b(?:PERNYATAAN|IKHTISAR|ANALISIS|FAKTOR)\b/i);
console.log('matchRoman:', matchRoman);

// Cek substring 120 karakter pertama
const sub = context.substring(0, 120);
console.log('sub:', sub);
console.log('test3 on sub:', /\b(?:III|IV|V|VI|VII)\b\s*(?:\.|\s)*\b(?:PERNYATAAN|IKHTISAR|ANALISIS|FAKTOR)\b/i.test(sub));
